### PR TITLE
Center content if there are not enough items

### PR DESCRIPTION
**Pull request by skyweb07**
This PR will calculate the remaining space and center content if there are not enough items to fill the window width using @hashemp206 solution from comments on https://github.com/ermalkaleci/CarbonKit/issues/102

### CODE REVIEW

**Comment by hashemp206** [comment]
oh thanks! use this code: previous solution has some issues! because while scrolling all the time I'm setting the scrollViewframe which cause scrollView doesnt bounce!

```objective-c

CGFloat selfWidth = CGRectGetWidth(self.bounds);
        if ( [_carbonSegmentedControl getWidth]<CGRectGetWidth(self.bounds))
        {
            CGFloat difference = selfWidth -  [_carbonSegmentedControl getWidth];
            self.frame = CGRectMake(difference/2.0f, 0, selfWidth, CGRectGetHeight(self.bounds));
            
        }
        else
        {
            CGRect frame = self.frame;
            if (!CGRectEqualToRect(frame, CGRectMake(0, 0, selfWidth, CGRectGetHeight(self.bounds))))
            {
                self.frame = CGRectMake(0, 0, selfWidth, CGRectGetHeight(self.bounds));
            }
        }
```

**Comment by skyweb07** [comment]
@hashemp206 didn't notice, thanks!!!

**Comment by MobileMon** [comment]
Doesn't work with tab bar controller and switching tabs

**Comment by O-mkar** [comment]
Doesn't work anymore with iOS 13

**Pull request closed without merging**
