### PR TITLE
add help to embed carbontab as childcontroller

### PR DESCRIPTION
**Pull request by wh33ler**
When you embed CarbonTabNavigationController within a viewcontroller and that viewcontroller will disappear the events won't get through to the tab-viewcontroller. 
I fixed this issue by calling the new function in the viewWillDisappear of the parent viewcontroller:

```
- (void)willMoveToParentViewController:(UIViewController *)parent{
    if (parent == NULL) {
        [carbonTabSwipeNavigation prepareForDisappearance];
    }
}
```

Let me know if I can help make it more elegant.

### CODE REVIEW

**Comment by ermalkaleci** [comment]
Hey @wh33ler 
Thank you for the PR :+1:  and sorry for late review. I have been really busy.
Yes we can make it more elegant without calling the method like you have described above. We can call the method when CarbonTabSwipeNavigation instance call `dealloc`
screen shot 2016-03-18 at 12 25 43
Please make this change and also remove `prepareForDisappearance` from header. I don't think it should be a public method.

Thanks :)

**Comment by wh33ler** [comment]
should be fixed

**Comment by wh33ler** [comment]
I fixed it as wanted. Thanks for the help

**Comment by wh33ler** [comment]
But when I think about it... I won't solve the problem if the holding viewcontroller disappears without being  deallocated (like in navigation bar history). Then the events won't get through even though the base controller gets those events.

**Comment by ermalkaleci** [comment]
This seems to have a simpler solution without calling extra methods
screen shot 2016-03-22 at 14 26 34

**Comment by ermalkaleci** [comment]
https://github.com/ermalkaleci/CarbonKit/tree/appear_disappear_issue

**Comment by ermalkaleci** [comment]
@wh33ler branch merged and pod updated

**Pull request closed without merging**
