### PR TITLE
Rewrote some constraint logic to be more "auto layout" friendly.

### PR DESCRIPTION
**Pull request by troystump**
This is an optimization in the CarbonKitTabNavigation class. We have removed some initial frame setting of views. Also, new constraint logic honors the top layout guide, which allows us to completely remove the tabTopConstraint variable, as well as all status bar frame logic.

### CODE REVIEW

**Comment by ermalkaleci** [comment]
Hello Troy,
You have removed some constraints that support auto-rotate. Sorry, I can't merge this request

**Comment by troystump** [comment]
Hey there,
Sorry about the rotation issue... I have since fixed made the fix to resolve that regression. My apologies!

I have a final pull request after this one which I think you will like, so I'm hoping we can merge this :)

Thanks!

**Comment by troystump** [comment]
Hi there,

I have fixed the device rotation issue, sorry about that. Please help me to merge this with your approval, thanks!

**Comment by ermalkaleci** [comment]
iPad rotation issue. I also want to have the code friendly but we need to make it carefully.
I very appreciate your contribution. Thank you for doing this :+1:

**Comment by troystump** [comment]
Hey man, I totally understand and appreciate your gated check-in style :)

Sorry, it was getting super late last night so I had a few "duh" moments in the constraints during rotation. I have committed a sensible fix which should resolve all rotational issues.

**Pull request merged**
